fix shellcheck errors

diff --git a/bin/generate-branch-name b/bin/generate-branch-name
--- a/bin/generate-branch-name
+++ b/bin/generate-branch-name
@@ -5,7 +5,7 @@ usage() {
 	echo "usage:" >&2
 	echo "  $(basename "${0}") <prefix> <string>" >&2
 
-	if ! [ -z "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/genpass b/bin/genpass
--- a/bin/genpass
+++ b/bin/genpass
@@ -2,10 +2,10 @@
 
 usage() {
 	echo "usage:" >&2
-	echo "  $(basename $0) <args...>" >&2
+	echo "  $(basename "${0}") <args...>" >&2
 	echo "generate a stable and 'secure' password based on <args...>" >&2
 
-	if ! [ -z "${1}" ]; then echo "error: ${1}" > &2; fi
+	if [ -n "${1}" ]; then echo "error: ${1}" > &2; fi
 
 	exit 1
 }
diff --git a/bin/has-branch b/bin/has-branch
--- a/bin/has-branch
+++ b/bin/has-branch
@@ -3,13 +3,13 @@
 usage() {
 	echo "  test whether <branch> exists locally or on the remote" >&2
 	echo "usage:" >&2
-	echo "  $(basename $0) <branch>" >&2
+	echo "  $(basename "${0}") <branch>" >&2
 
-	if ! [ -z "$1" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "$1" ]; then echo "error: ${1}" >&2; fi
 
 	exit 1
 }
 
 if [ -z "${1}" ]; then usage "<branch> required"; fi
 
-./has-local-branch.sh "${1}" || ./has-remote-branch.sh "${1}"
+has-local-branch "${1}" || has-remote-branch "${1}"
diff --git a/bin/has-remote-branch b/bin/has-remote-branch
--- a/bin/has-remote-branch
+++ b/bin/has-remote-branch
@@ -3,9 +3,9 @@
 usage() {
 	echo "  test whether <branch> exists on the remote" >&2
 	echo "usage:" >&2
-	echo "  $(basename $0) <branch>" >&2
+	echo "  $(basename "${0}") <branch>" >&2
 
-	if ! [ -z "$1" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "$1" ]; then echo "error: ${1}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/set-password b/bin/set-password
--- a/bin/set-password
+++ b/bin/set-password
@@ -7,7 +7,7 @@ usage() {
 	echo "contexts is any list of tokens, such as URL, host, or username" >&2
 	echo "password will be provided on stdin" >&2
 
-	if ! [ -z "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/startpr b/bin/startpr
--- a/bin/startpr
+++ b/bin/startpr
@@ -4,7 +4,7 @@ usage() {
 	echo "usage:" >&2
 	echo "  $(basename "${0}") <title>" >&2
 
-	if ! [ -z "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
 
 	exit 1
 }
@@ -16,7 +16,7 @@ if ! has-staged-changes; then usage "Expected staged changes."; fi
 # TODO: update base branch before opening PR
 
 bodyfile="$(mktemp)"
-echo "${@}\n" > "${bodyfile}"
+printf "%s\n\n" "${?}" > "${bodyfile}"
 nano "${bodyfile}"
 
 title="$(head -n 1 "${bodyfile}")"
