add color to error output

diff --git a/bin/get-password b/bin/get-password
--- a/bin/get-password
+++ b/bin/get-password
@@ -6,7 +6,7 @@ usage() {
 	echo "  $(basename "${0}") <contexts...>" >&2
 	echo "contexts is any list of tokens, such as URL, host, or username" >&2
 
-	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/get-pull-request-link b/bin/get-pull-request-link
--- a/bin/get-pull-request-link
+++ b/bin/get-pull-request-link
@@ -7,7 +7,7 @@ usage() {
 	echo "  $(basename "${0}") [<Pull Request Number>]" >&2
 	echo >&2
 
-	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
 
 	exit 1
 }
@@ -26,7 +26,7 @@ domain="$(sed -E -e 's/^(git@|https:\/\/)([a-zA-Z0-9._-]+)(\/.*|:.*)/\2/' <<< "$
 
 if [ -z "${1}" ]; then
 	echo "https://${domain}/$(get-repo-name)/pulls" >&1
-	
+
 else
 	echo "https://${domain}/$(get-repo-name)/pull/${1}" >&1
 fi
diff --git a/bin/get-repo-name b/bin/get-repo-name
--- a/bin/get-repo-name
+++ b/bin/get-repo-name
@@ -4,7 +4,7 @@ usage() {
 	echo "usage:" >&2
 	echo "  $(basename "${0}")" >&2
 
-	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/prompt b/bin/prompt
--- a/bin/prompt
+++ b/bin/prompt
@@ -8,7 +8,7 @@ usage() {
 	echo "  -n    default response will be 'n'" >&2
 	echo >&2
 
-	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
 
 	exit 1
 }
diff --git a/bin/startpr b/bin/startpr
--- a/bin/startpr
+++ b/bin/startpr
@@ -13,7 +13,7 @@ usage() {
 	echo "  -b    The branch name to use (because it's different from the commit or title)." >&2
 	echo >&2
 
-	if [ -n "${1}" ]; then echo "error: ${1}" >&2; fi
+	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
 
 	exit 1
 }
