lint: fix option handling and add more options

diff --git a/bin/lint b/bin/lint
--- a/bin/lint
+++ b/bin/lint
@@ -3,13 +3,19 @@
 set -e
 
 usage() {
-	echo "Description" >&2
+	echo "Run a randomly selected linter* on some randomly selected files**." >&2
 	echo >&2
 	echo "usage:" >&2
-	echo "  $(basename "${0}") [-x] <arguments>" >&2
+	echo "  $(basename "${0}") [list|fix|all]" >&2
 	echo >&2
 	echo "options:" >&2
-	echo "  -x    Some unknown option" >&2
+	echo "  list  Dump a list of the files we might be interested in." >&2
+	echo "  fix   Maybe try to clean some errors." >&2
+	echo "  all   Lint the whole project if the index is clean." >&2
+	echo >&2
+	echo "footnotes:" >&2
+	echo "  *     linter not really randomly selected." >&2
+	echo "  **    files not really randomly selected either." >&2
 	echo >&2
 
 	if [ -n "${1}" ]; then echo -e "${A_CS} error: ${1} ${N_CS}" >&2; fi
@@ -18,8 +24,6 @@ usage() {
 }
 
 list() {
-	echo -e "${S_CS} Collecting files... ${N_CS}" >&2
-
 	if [ -z "$(git diff --staged)" ]; then
 		git diff --name-only | sed -E -e '/\.(js|ts)$/!d'
 	else
@@ -28,11 +32,21 @@ list() {
 }
 
 lint() {
+	echo -e "${S_CS} Linting... ${N_CS}" >&2
 	list | xargs eslint
+	echo -e "${S_CS} Done ${N_CS}" >&2
+}
+
+lint-all() {
+	echo -e "${S_CS} Linting... ${N_CS}" >&2
+	list | xargs eslint --ignore-pattern '**\.**'
+	echo -e "${S_CS} Done ${N_CS}" >&2
 }
 
 lint-fix() {
+	echo -e "${S_CS} Linting & Fixing... ${N_CS}" >&2
 	list | xargs eslint --fix
+	echo -e "${S_CS} Done ${N_CS}" >&2
 }
 
 npm-lint() {
@@ -46,21 +60,39 @@ npm-lint() {
 
 if [[ "${1}" =~ ^-?-h(elp)?$ ]]; then usage ''; fi
 
-if [[ "${1}" =~ ^(--)?fix$ ]]; then
-	lint-fix
+run_any=1
+run_all=0
+while (( $# > 0 )); do
+	case "${1}" in
+		list)
+			list
+			run_any=0
+			;;
+		fix)
+			lint-fix && echo -e "${S_CS} Done ${N_CS}" >&2
+			run_any=0
+			;;
+		all)
+			run_all=1
+			;;
+		*)
+			usage "Unknown argument: ${1}"
+			;;
+	esac
+	shift
+done
 
-elif [[ "${1}" =~ ^(--)?list$ ]]; then
-	list
+if [ "${run_any}" == '1' ]; then
+	if [ "${run_all}" == '1' ]; then
+		if [ -z "$(list)" ]; then
+			echo -e "${S_CS} No files in index. Linting the whole project ${N_CS}" >&2
+			npm-lint
 
-elif [ -n "${1}" ]; then
-	usage "Unknown argument: ${1}"
-
-else
-	if [ -z "$(list)" ]; then
-		npm-lint
-
+		else
+			lint-all && echo -e "${S_CS} Index is clean. Linting the whole project ${N_CS}" >&2 && sleep 2 && npm-lint
+		fi
 	else
-		lint && echo -e "${S_CS} Index is clean. Running whole project ${N_CS}" >&2 && sleep 2 && npm-lint
+		lint
 	fi
 fi
 
